
//Generated by the IDL-to-C#-compiler MiddCorIdl
//Source: hello.idl
//Saturday, April 10, 2004, 10:47:44 PM

using System;
using System.Collections;
using MiddTec;


//Types

namespace HelloCorba
{
	namespace GreetingsPackage
	{
	}
}

//Interfaces

namespace HelloCorba
{
	public interface Greetings : GreetingsOperations, MiddTec.CORBA.Object, MiddTec.CORBA.portable.IDLEntity
	{
	}
}

//Operations

namespace HelloCorba
{
	public interface GreetingsOperations
	{
		string hello(  string a_sendMsg  );
	}
}

//Helpers

namespace HelloCorba
{
	public class GreetingsHelper
	{
		private static string _id = "IDL:HelloCorba/Greetings:1.0";
		public static string id()
		{
			return _id;
		}
		private static MiddTec.CORBA.TypeCode _typeCode = null;
		public static MiddTec.CORBA.TypeCode type()
		{
			if ( _typeCode==null )
			    _typeCode = create_type();
			return _typeCode;
		}
		public static MiddTec.CORBA.TypeCode create_type()
		{
			MiddTec.CORBA.TypeCode typeCode = MiddTec.CORBA._ORB.ORB().create_interface_tc( id(), "Greetings" );
			return typeCode;
		}
		public static void insert( MiddTec.CORBA.Any a, Greetings s )
		{
			a.type( type());
			write( a.create_output_stream(), s );
		}
		public static Greetings extract( MiddTec.CORBA.Any a )
		{
			return read( a.create_input_stream() );
		}
		public static void write( MiddTec.CORBA.portable.OutputStream outpStream, Greetings s )
		{
			outpStream.write_Object ((MiddTec.CORBA.Object) s);
		}
		public static Greetings read( MiddTec.CORBA.portable.InputStream inpStream )
		{
			return narrow ( inpStream.read_Object() );
		}
		public static Greetings narrow( MiddTec.CORBA.Object obj )
		{
			if( obj == null )
			{
				return null;
			}
			if ( obj is Greetings )
			{
				return (Greetings) obj;
			}
			if( obj._is_a( id() ) )
			{
				_GreetingsStub stub = new _GreetingsStub();
				stub._set_delegate(((MiddTec.CORBA.portable.ObjectImpl)obj)._get_delegate());
				return stub;
			}
			throw new MiddTec.CORBA.BAD_PARAM("Narrow failed");
		}
	}
	namespace GreetingsPackage
	{
	}
}

//Stubs

namespace HelloCorba
{

	public class _GreetingsStub : MiddTec.CORBA.portable.ObjectImpl, Greetings
	{
		private string[] ids = {"IDL:HelloCorba/Greetings:1.0"};
		public override string[] _ids()
		{
			return ids;
		}
		public string hello(  string a_sendMsg )
		{
			MiddTec.CORBA.portable.InputStream ins = null;
			while( true )
			{
				try
				{
					MiddTec.CORBA.portable.OutputStream outs = _request( "hello", true );
					outs.write_string( a_sendMsg );
					ins = _invoke( outs );
					string result = ins.read_string();
					return result;
				}
				catch( MiddTec.CORBA.portable.RemarshalException )
				{
				}
				catch( MiddTec.CORBA.portable.ApplicationException ax )
				{
					String id = ax.getId();
					throw new MiddTec.CORBA.MARSHAL ( id );
				}
				finally
				{
					this._releaseReply( ins );
				}
			}
		}
	}
}

//POA

namespace HelloCorba
{

	public abstract class GreetingsPOA : MiddTec.PortableServer.Servant, GreetingsOperations, MiddTec.CORBA.portable.InvokeHandler
	{
		private string[] ids = {"IDL:HelloCorba/Greetings:1.0"};
		public override string[] _all_interfaces(MiddTec.PortableServer.POA poa, byte[] objectId)
		{
			return ids;
		}
		public Greetings _this()
		{
			return GreetingsHelper.narrow( base._this_object( ) );
		}
		public Greetings _this( MiddTec.CORBA.ORB orb )
		{
			return GreetingsHelper.narrow( base._this_object( orb ) );
		}
		virtual public string hello(  string a_sendMsg  ){ return (string)(System.Object) null ;}
		public MiddTec.CORBA.portable.OutputStream _invoke( string method, MiddTec.CORBA.portable.InputStream ins, MiddTec.CORBA.portable.ResponseHandler resh )
		{
			MiddTec.CORBA.portable.OutputStream outs = null;
			switch( method )
			{
				case "hello":
				{
					string a_sendMsg = ins.read_string();
					string result = this.hello(  a_sendMsg );
					outs = resh.createReply();
					outs.write_string( result );
					break;
				}
				default:
					throw new MiddTec.CORBA.BAD_OPERATION();
			}
			return outs;
		}
	}
}

//POATie

namespace HelloCorba
{
	public class GreetingsPOATie : GreetingsPOA
	{
		public GreetingsPOATie( GreetingsOperations impl ) 
		{
			this._impl = impl;
		}
		public GreetingsPOATie( GreetingsOperations impl, MiddTec.PortableServer.POA poa ) 
		{
			this._impl = impl;
			this._poa_tie = poa;
		}
		public GreetingsOperations _delegate
		{
			set
			{
				this._impl = value;
			}
			get
			{
				return this._impl;
			}
		}
		override public MiddTec.PortableServer.POA _default_POA()
		{
			if(_poa_tie != null)
			{
				return _poa_tie;
			}
			else
			{
				return base._default_POA();
			}
		}
		override public string hello(  string a_sendMsg  )
		{
			return _impl.hello(  a_sendMsg  );
		}
		private GreetingsOperations _impl = null;
		private MiddTec.PortableServer.POA _poa_tie = null;
	}
}
